name: "Zephyr Preview Environment"
description: "Create a preview environment using Zephyr (PR-only action)"
inputs:
  github_token:
    description: "The GitHub token to use for the action"
    required: true
outputs:
  preview_environment_urls:
    description: "The URLs of the created preview environments"
runs:
  using: "node20"
  main: "index.js"
