name: "Zephyr Preview Environments"
description: "Create preview environments using Zephyr (PR-only action)"
author: "ZephyrCloudIO"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true

outputs:
  preview_environments_urls:
    description: "URLs of created preview environments"

runs:
  using: "node20"
  main: "index.js"
