name: Zephyr Preview Environments

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  deployments: write # allow creating deployments
  pull-requests: write # allow commenting on PRs
  contents: read # minimal read access to repo, if needed

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10.26.0
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build Examples
        env:
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
        run: pnpm run build:examples

      - name: Zephyr Preview Environments
        uses: ./
        id: zephyr-preview-environment-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Preview deployment URL
        if: steps.zephyr-preview-environment-action.outputs.preview_environments_urls
        run: echo "Preview available at ${{ steps.zephyr-preview-environment-action.outputs.preview_environments_urls }}"
