name: Zephyr Preview Environments

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  deployments: write # allow creating deployments
  pull-requests: write # allow commenting on PRs
  contents: read # minimal read access to repo, if needed

env:
  NODE_VERSION: 24

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build Examples
        env:
          ZE_CI_TOKEN: ${{ secrets.ZE_CI_TOKEN }}
        run: pnpm run build:examples

      - name: Zephyr Preview Environments
        uses: ./
        id: zephyr-preview-environment-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Preview deployment URL
        if: steps.zephyr-preview-environment-action.outputs.preview_environments_urls
        run: echo "Preview available at ${{ steps.zephyr-preview-environment-action.outputs.preview_environments_urls }}"
